// Generated by BiocJobs 0.99.0 from the 'inspect' job declared in
// Bioconductor package DropletUtils (inst/biocjobs/). Do not edit;
// regenerate with: Rscript -e 'BiocJobs::biocjobsCLI()' nextflow <pkg> inspect

process INSPECT {
    tag "${meta.id}"
    container 'bioconductor/bioconductor_docker:RELEASE_3_23'
    cpus 1
    memory '4 GB'
    disk '10 GB'

    input:
    // meta: map identifying the unit of work; meta.id names the tag
    // loom_file: SingleCellLoomExperiment (loom)
    tuple val(meta), path(loom_file)

    output:
    tuple val(meta), path('outfile.txt'), emit: outfile

    script:
    """
    Rscript -e 'BiocJobs::execJob("DropletUtils", "inspect")' \\
        --loom_file '${(loom_file as String).replace("'", "'\\''")}' \\
        --outfile 'outfile.txt'
    """

    stub:
    """
    touch 'outfile.txt'
    """
}
